# https://docs.travis-ci.com/user/customizing-the-build/

os:
  - linux
  - osx
sudo: false
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
before_install:
  - node --version
  - npm --version
install:
  - npm install
script:
  - npm run dist
